[build]
  command = "pnpm install --include=dev && pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

#[context.production.environment]
#  NODE_ENV = "production"